### ISSUE TITLE
Error `E171: Missing :endif` probably introduced by `timers` commit

### ISSUE THREAD

**Issue by tomcham** [ensime/ensime-vim#388] opened 2017-04-03 18:25 UTC
I removed ensime from my ivy cache and regenerated the ensime configs.

Tested with the following config
```
call plug#begin('~/.config/nvim/plugged')
Plug 'https://github.com/ensime/ensime-vim', { 'commit': 'bdc8d35e7d6e195ce8305153ad3f542e280e2e06' }
call plug#end()
```
Neovim 
```
NVIM 0.1.7
Build type: RelWithDebInfo
Compilation: /usr/local/Homebrew/Library/Homebrew/shims/super/clang -Wconversion -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -O2 -g -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim-20170318-55698-1bprndh/neovim-0.1.7/build/config -I/tmp/neovim-20170318-55698-1bprndh/neovim-0.1.7/src -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/include -I/usr/local/opt/gettext/include -I/usr/include -I/usr/include -I/tmp/neovim-20170318-55698-1bprndh/neovim-0.1.7/build/src/nvim/auto -I/tmp/neovim-20170318-55698-1bprndh/neovim-0.1.7/build/include
```

### Steps to reproduce

1.  Use above neovim config and run `:PlugInstall`
2. Open a scala file

### Expected behaviour
No error

### Actual behaviour
Getting below error:

```
Error detected while processing BufEnter Auto commands for "*.scala":
error caught in request handler '~/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py:autocmd:BufEnter:*.scala ('server/src/main/scala/Application.scala',)':
Traceback (most recent call last):
  File "~/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py", line 176, in au_buf_enter
    super(NeovimEnsime, self).au_buf_enter(*args, **kwargs)
  File "~/.config/nvim/plugged/ensime-vim/ensime_shared/ensime.py", line 22, in wrapper2
    create_client=create_client)
  File "~/.config/nvim/plugged/ensime-vim/ensime_shared/ensime.py", line 95, in current_client
    create_client=create_client)
  File "~/.config/nvim/plugged/ensime-vim/ensime_shared/ensime.py", line 105, in client_for
    client = self.create_client(config_path)
  File "~/.config/nvim/plugged/ensime-vim/ensime_shared/ensime.py", line 124, in create_client
Error detected while processing function remote#define#AutocmdBootstrap:
line    7:
E171: Missing :endif
```
Reverting back to commit https://github.com/ensime/ensime-vim/commit/511f60911ecdeb6deb732d8a383892a0a1de63a8 works.

**Comment by yyadavalli** [comment] 2017-04-03 18:58
Did you run `:UpdateRemotePlugins` after installing?

**Comment by tomcham** [comment] 2017-04-03 19:31
Yeah

Also getting this error:

```
"server/src/main/scala/Application.scala" 277L, 12001C
Error detected while processing function 13[30]..<SNR>19_callback:
line   33:
Vim(call):error caught in request handler '~/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py:autocmd:BufEnter:*.scala ('server/src/main/scala/Application.scala',)':
```

**Comment by jan0sch** [comment] 2017-04-04 09:00
I can confirm this error using neovim 0.1.7, ensime 1.12.9 and latest ensime-vim (via pathogen).
The interesting part of the error message seems to be the last lines:

```
line    7:
E171: Missing :endif
```

Some research indicates that this might be related to calling python from vimscript.

**Comment by travishegner** [comment] 2017-04-04 12:48
Please see this comment: https://github.com/ensime/ensime-vim/issues/386#issuecomment-290740703

As mentioned in the linked comment, I believe I have it traced back to `EnTick` not being registered correctly as a function in neovim. Yes, I am confident that I am running neovim that is loading a file that contains the definition for `EnTick`

The work-around prevents the error message, but I still have a non-functioning ensime. Looking at the .ensime_cache/server.log after performing the work-around I have `Error: Could not find or load main class org.ensime.server.Server`.

I'm using maven with scala 2.11 for my project, and another oddity that I noticed is that after running `mvn ensime:generate`, I get this message:
```
[WARNING] The POM for org.ensime:server_2.11:jar:2.0.0-SNAPSHOT is missing, no dependency information available
```
Given that, I searched my `~/.m2/repository` for the mentioned jar file and it doesn't exist. Nor could I find a `2.0.0-SNAPSHOT` version of ensime server in maven central: https://mvnrepository.com/artifact/org.ensime/server_2.11.

With the work-around in place, I can see that the ensime server is attempting to be started, and `.ensime_cache/server.pid` contains a pid. That pid, however, looks like this:

```bash
$ ps -ef | grep 20784
thegner  20784 20768  0 08:43 pts/0    00:00:00 [java] <defunct>
```

Please let me know if I can provide an further troubleshooting assistance.

**Comment by 2chilled** [comment] 2017-04-05 04:56
I made quite the same observations as @travishegner using neovim.

**Comment by ktonga** [comment] 2017-04-05 14:12
@travishegner Ok. it seems that your build tool integration does not support generating `ensimeServerJars` field in `.ensime` so the error might be related to ensime-vim trying to bootstrap the server and some kind of incompatibility with the new `timers` approach. Any idea @Kazy ?

Could you please provide the `.ensime` file maven is generating?

Also it would be helpful if you started vim like this: `ENSIME_VIM_DEBUG=1 vim` and then attached your `ensime-vim.log`

**Comment by 2chilled** [comment] 2017-04-05 15:08
@ktonga I had the same problem with EnTick by using a .ensime file generated by sbt. neovim claimed that `EnTick` command is not defined.

**Comment by Kazy** [comment] 2017-04-05 15:36
The error only exists with Neovim 1.7, but is fixed when using the current HEAD. The actual bug is this one: https://github.com/neovim/neovim/issues/5821. As mentioned in the issue, if you first do `:call EnTick()` before opening a Scala file, and then open it, it works correctly.

@ktonga: we can revert the commit until the fix is in a stable release (2.0 apparently). Since there is a (manual) workaround, I'll try to see if we can call the function to force Neovim to register it.

**Comment by Kazy** [comment] 2017-04-05 15:53
If some of you could test the fix with the following commit (https://github.com/Kazy/ensime-vim/commit/2ab94df5d5d1b59937e2faecb5dedea8ae0b651a) to confirm it works that would be great :)

**Comment by ktonga** [comment] 2017-04-05 15:53
Oh, that's why I'm not experiencing this issue, coz I'm on `NVIM v0.2.0-dev`

Ok @Kazy let's try to automate the workaround :smile:  I'd prefer that over reverting. If it isn't possible then we should revert.

Thanks for taking care so quickly.

**Comment by tomcham** [comment] 2017-04-05 17:37
@Kazy fix works for me. Using `NVIM 0.1.7`

**Comment by travishegner** [comment] 2017-04-05 17:38
@Kazy the work-around prevents the error message for me also. I'm still having a separate issue with `mvn ensime:generate` not downloading the correct ensime server version, so I will file a separate issue for that.

**Comment by Kazy** [comment] 2017-04-05 17:46
Good to know, thanks for testing !

**Closed** 2017-04-05 17:54 UTC

**Comment by Jacoby6000** [comment] 2017-04-05 18:14
I happened to stumble on this just now. I'm still having the issue even with the PR. Using `NVIM 0.1.7` as well with `ensime-sbt 1.12.9`

```
"~/projects/voz/libraries/voz-common-core/src/main/scala/voz/common/AppName.scala" 27L, 1217C
Error detected while processing BufEnter Auto commands for "*.scala":
error caught in request handler '/Users/jacobbarber/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py:autocmd:BufEnter:*.scala ('libraries/voz-common-core/src/main/scala/voz/common/AppName.scala',)':
Traceback (most recent call last):
  File "/Users/jacobbarber/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py", line 179, in au_buf_enter
    self._vim.command('call EnTick()')
  File "/usr/local/lib/python2.7/site-packages/neovim/api/nvim.py", line 201, in command
    return self.request('vim_command', string, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/neovim/api/nvim.py", line 129, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
NvimError: Vim(return):no request handler registered for "/Users/jacobbarber/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py:function:EnTick"
Error detected while processing function remote#define#AutocmdBootstrap:
line    7:
E171: Missing :endif
```

I appear to have PR #389 

```
jacob.barber ~/.config/nvim/plugged/ensime-vim (master) $ git log
commit 271d91b428033f40cb24173bf43e9662a1b1ccf0
Author: Boullier Jocelyn <kazoomy@gmail.com>
Date:   Wed Apr 5 19:54:20 2017 +0200

    Close #388: Adds workaround (#389)

    * Close #388: Adds workaround

    * Adds TODO comment for the removal of the workaround
```

My stacktrace is a bit different, so it might be a new issue.  I just saw mentions of EnTick in here and in my stacktrace so I figured I'd post here.

**Comment by Kazy** [comment] 2017-04-05 18:24
Does it happen consistently ? Did you run `UpdateRemotePlugins` ?

**Comment by Jacoby6000** [comment] 2017-04-05 19:52
Ah, I didn't realize I'd have to run `UpdateRemotePlugins`.  It seems to work now, aside from this error which I assume is unrelated: 

```
jacob.barber ~/projects/voz (master) $ cat ./.ensime_cache/ensime-vim.log
INFO     <2017-04-05 14:50:12,099> (client.py:83) - Initializing project - /Users/jacobbarber/projects/voz
ERROR    <2017-04-05 14:50:14,545> (client.py:212) - connection error: Handshake status 404
Traceback (most recent call last):
  File "/Users/jacobbarber/.config/nvim/plugged/ensime-vim/ensime_shared/util.py", line 48, in catch
    yield
  File "/Users/jacobbarber/.config/nvim/plugged/ensime-vim/ensime_shared/client.py", line 228, in connect_ensime_server
    self.ws = websocket.create_connection(self.ensime_server, **options)
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 489, in create_connection
    websock.connect(url, **options)
  File "/usr/local/lib/python2.7/site-packages/websocket/_core.py", line 219, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/local/lib/python2.7/site-packages/websocket/_handshake.py", line 67, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/local/lib/python2.7/site-packages/websocket/_handshake.py", line 123, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d", status)
WebSocketBadStatusException: Handshake status 404
```

**Comment by tomcham** [comment] 2017-04-05 19:54
@Jacoby6000 See https://github.com/ensime/ensime-vim/issues/386

**Comment by Jacoby6000** [comment] 2017-04-05 19:55
:+1:
