### ISSUE TITLE
ensime-gradle + ensime-vim incompatibility

### ISSUE THREAD

**Issue by codyrioux** [ensime/ensime-vim#194] opened 2016-03-17 05:01 UTC
Using the latest gradle integration located on https://ensime.github.io I'm running into an issue in which I get an error about the property "scala-version" not existing. Python is throwing this specifically because it is missing from the config map loaded in the loader.py
```
Error detected while processing function ensime#au_buf_enter[1]..<SNR>116_call_plugin:
line   15:
E605: Exception not caught: <type 'exceptions.KeyError'>:'scala-version'  
```

If I generate the .ensime file using sbt (same dependencies) I get a much different sized file, and it functions. The second solution is to edit `ensime_shared/launcher.vim` line 223 from:

```python
            #original
            "(", " ").replace(")", " ").replace('"', "").split(" :")
            #new
            "(", " ").replace(")", " ").replace('"', "").split(":") #space before colon removed
```

**Versions**
Gradle: Gradle 2.10
SBT: 0.13
vim: VIM - Vi IMproved 7.3 (2010 Aug 15, compiled Oct 27 2015 16:22:14)
macvim: VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Mar 16 2016 15:52:28)

Regardless of wether I use SBT or have made the edit to the launcher.py I'm getting a message on my vim status line:
```
not found: \e
```

It appears to be refreshing, so I suspect the cause is running in a loop.
Upon quitting I'm hanging on the message and have to force quit vim:
```
:EnClasspath to set a classpath
```

I suspect the initial issue is with the ensime-gradle plugin, but I thought I'd check here about the rest first. If I can be of any help by writing documentation after this, or even a pull request after getting some input I'm certainly willing to do so.

**Comment by codyrioux** [comment] 2016-03-17 05:14
Gist with the generated .ensime files [here](https://gist.github.com/codyrioux/223b798cfdd1b61e01b4).

**Comment by ChrisCoffey** [comment] 2016-03-18 02:49
If you're up for extending the launcher to support both plugins that's great! From the docs it looks like the original code was built to support only sbt, hence the break you're seeing. 

As for the looping issue, could you take a look through your `.ensime-vim` log & post the 150 or so lines before you killed vim to a gist?

**Comment by codyrioux** [comment] 2016-03-18 04:55
Hey Chris,

I would be up for extending the launcher. I was unaware that the other build tools weren't supported. Once we get the rest of these details worked out I'll dig into what it'll take to support gradle ensime files. I used the sbt generated .ensime file and then ran ` :EnClasspath .`. Things seem mostly functional now (an :EnRename worked), I get some messages about the ensime server starting and the editor is responsive, and quits correctly.

I am still getting the `not found: \e` message, and here is the the associated [ensime-vim.log](https://gist.github.com/codyrioux/a4835a82ace07ebdf684)

I'll dig through the log as well, once things are working with the sbt generated .ensime file and I know I have a sane vim environment I'll begin the task of adding launcher support for gradle.

Thanks!

**Comment by ches** [comment] 2016-03-18 13:38
It might be worth looking at the thread on #168 and considering if it even makes sense for ensime-vim to try to handle the classpath generation when the build tool plugins should already do a good job of that—the Ensime plugins for most other editors appear to just defer to them for the task.

The ensime-server launching part shouldn't need to be build tool-specific (and doesn't appear that it is in ensime-vim). Seems like the plugin's parsing of `.ensime` just needs to be made a little more lenient to tolerate different but valid formatting of the file output by different tools.

**Comment by jvican** [comment] 2016-03-18 14:03
Just for the record, support for Gradle was added recently, so we haven't updated this to work with other build tools. I'd like it to be compatible with more @codyrioux  :+1:

**Comment by codyrioux** [comment] 2016-03-25 18:13
Sorry about the delay in responding here, I'm presenting at Strata + end of quarter at work has me a little held up. I should be able to dig in much deeper next weekend.

**Comment by codyrioux** [comment] 2016-04-06 00:01
I need to ensure a sane environment before I start working on the gradle support. I've got an SBT project that seems to work just fine. Judging from the log it looks like the server and vim are interacting well with one another but I can't test simple things like `:EnType` since the status line gets blown over by the `not found: \e` message.

I don't have much experience debugging vim plugins, is there some way to easily determine what line of vimscript the error message came from? That should help me track it down.

**Comment by ChrisCoffey** [comment] 2016-04-06 01:47
I think the problem you're seeing is caused by an invalid escape sequence due to some incorrect quoting. Should be addressed by #218

**Comment by ChrisCoffey** [comment] 2016-04-07 13:55
@codyrioux Let me know if you're still blocked now that #218 has landed

**Comment by codyrioux** [comment] 2016-04-07 20:04
@ChrisCoffey Thanks! Looks like it works, I have a verified sane environment in a very small SBT project. Going to convert it to a gradle project and move forward from there on ensuring compatibility.

**Comment by codyrioux** [comment] 2016-04-07 21:36
A little bit of reformatting of the produced .ensime file from gradle seemed to do the trick, so I've confirmed it isn't a fundamental issue about the output. Just some most robust parsing is necessary. I'll work on this in the near future.

**Comment by codyrioux** [comment] 2016-04-08 17:22
I see your WIP commit on your fork. I had wondered if you'd be open to adding a dependency on a full S-expression parser. Is there anything I can do to assist?

**Comment by ches** [comment] 2016-04-08 17:25
@codyrioux You beat me to finishing my pull request comment before I could comment here 😄   See what you think of #235, and it'd be great to know if it handles the Gradle plugin output now.

**Comment by codyrioux** [comment] 2016-04-08 17:59
@ches Tested on an admittedly simple file and the sbt version still functions, and the gradle version functions at least as well as the sbt version does. Looks like you've solved it!

Tested With:

`Plug 'ches/ensime-vim', { 'branch': 'dot-ensime-sexp-parser' }`

Thanks.

**Comment by ChrisCoffey** [comment] 2016-06-02 11:56
I believe this has been resolved, I'll reopen if this turns out not to be the case.

**Closed by ChrisCoffey** 2016-06-02 11:56 UTC
