### ISSUE TITLE
ensime-vim.log: WebSocketBadStatusException: Handshake status 404

### ISSUE THREAD

**Issue by andykais** [ensime/ensime-vim#386] opened 2017-03-22 19:22 UTC
upon opening a scala file within a project, the vim command line states:
```
[ensime] Server has been started...
A WS exception happened, 'ensime-vim' has been disabled. For more information, have a look at the logs in '.ensime_cache'
```
and I cannot run any ensime commands

## logs
.ensime_cache/ensime-vim.log:
```text
INFO     <2017-03-22 15:03:42,062> (client.py:83) - Initializing project - /home/andrew/Build/dev/telebum2/services/web-api
ERROR    <2017-03-22 15:03:45,021> (client.py:212) - connection error: Handshake status 404
Traceback (most recent call last):
  File "/home/andrew/.dotfiles/config/nvim/plugged/ensime-vim/ensime_shared/util.py", line 49, in catch
    yield
  File "/home/andrew/.dotfiles/config/nvim/plugged/ensime-vim/ensime_shared/client.py", line 228, in connect_ensime_server
    self.ws = websocket.create_connection(self.ensime_server, **options)
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 487, in create_connection
    websock.connect(url, **options)
  File "/usr/lib/python2.7/site-packages/websocket/_core.py", line 214, in connect
    self.handshake_response = handshake(self.sock, *addrs, **options)
  File "/usr/lib/python2.7/site-packages/websocket/_handshake.py", line 65, in handshake
    status, resp = _get_resp_headers(sock)
  File "/usr/lib/python2.7/site-packages/websocket/_handshake.py", line 122, in _get_resp_headers
    raise WebSocketBadStatusException("Handshake status %d", status)
WebSocketBadStatusException: Handshake status 404
```

.ensime_cache/server.log:
```text
15:03:44.076 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
15:03:44.090 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
15:03:44.095 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
15:03:44.132 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
15:03:44.191 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:42411
15:03:44.201 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 42411
15:03:44.209 INFO  None o.e.s.PortUtil$ - creating port file: /home/andrew/Build/dev/telebum2/services/web-api/.ensime_cache/port
15:03:44.367 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
15:03:44.368 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   OS : Linux
15:03:44.369 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Java : OpenJDK 64-Bit Server VM 25.121-b13, OpenJDK Runtime Environment 1.8.0_121-b13
15:03:44.369 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Scala version: version 2.12.1
15:03:44.370 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Ensime : 2.0.0-SNAPSHOT
15:03:44.370 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built with Scala version: 2.12.1
15:03:44.371 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built with sbt version: 0.13.13
15:03:44.371 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built from git sha: 2051fbff46770d4a1f059055ab9233dacf898740
15:03:44.372 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor -   Built on: 2017-03-03
15:03:44.380 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1:43515
15:03:44.381 INFO  None o.e.s.PortUtil$ - creating port file: /home/andrew/Build/dev/telebum2/services/web-api/.ensime_cache/http
15:03:45.014 DEBUG None o.e.s.DocsHandler - Sending response: Left(404 Not Found), for request: HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 0, cap: 0, components=0))
GET /jerky HTTP/1.1
Upgrade: websocket
```

### Neovim 0.1.7
```
pip2 install neovim sexpdata websocket-client
```
in editor:
```
:echo has('python')
1
:UpdateRemotePlugins
remote/host: python3 host registered plugins ['deoplete']                                                       
remote/host: python host registered plugins ['ensime.py']                                                       
remote/host: generated rplugin manifest: /home/andrew/.local/share/nvim/rplugin.vim   
```

### sbt 0.13.13
```
$ cat ~/.sbt/0.13/plugins/plugins.sbt
addSbtPlugin("org.ensime" % "sbt-ensime" % "1.12.7")
```

```
$ cat ~/.sbt/0.13/global.sbt
import org.ensime.EnsimeCoursierKeys._
ensimeServerVersion in ThisBuild := "2.0.0-SNAPSHOT"
```

## additional info
the troubleshooting page states to run 
```
rm -rf ~/.ivy2/cache/org.ensime
rm -rf ~/.ivy2/local/org.ensime
```
but neither `~/.ivy2/cache/org.ensime` or `~/.ivy2/local` folders exist

**Comment by ktonga** [comment] 2017-03-25 13:28
Hi @andykais with that setup I think ensime-vim should be using servers jars resolved by `sbt ensimeConfig` does that sbt command finish successfully?

**Comment by ktonga** [comment] 2017-03-25 13:31
There was a problem with ensime server binaries recently, please find `org.ensime` under your coursier cache (`.coursier/cache`) and wipe it out. Then run `sbt ensimeConfig` again and try starting vim after that.

**Comment by andykais** [comment] 2017-03-26 23:06
There is no `org.ensime` folder in `~/.coursier/cache` either, just this
```log
$ tree ~/.coursier/cache -L 3
/home/andrew/.coursier/cache
└── v1
    └── https
        ├── oss.sonatype.org
        └── repo1.maven.org
```
I should mention that `~/.ivy/cache` is populated with other folders as well.

`ensimeConfig` works correctly, at least as far as I know, creating a `.ensime` file with data in it, but vim responds with the same error

**Comment by ktonga** [comment] 2017-03-27 00:36
Could you please find the value of `:ensime-server-jars` within your `.ensime` file?. `ensimeConfig` should resolve them using coursier and place them under your coursier cache, and vim should use them to launch the server

**Comment by andykais** [comment] 2017-03-27 01:14
```log
 :ensime-server-jars ("/home/andrew/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/snapshots/org/ensime/monkeys_2.12/2.0.0-SNAPSHOT/monkeys_2.12-2.0.0-SNAPSHOT.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/zaxxer/HikariCP/2.6.0/HikariCP-2.6.0.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.4.17/akka-actor_2.12-2.4.17.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.12/2.4.17/akka-slf4j_2.12-2.4.17.jar" "/home/andrew/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/snapshots/org/ensime/api_2.12/2.0.0-SNAPSHOT/api_2.12-2.0.0-SNAPSHOT.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm/5.2/asm-5.2.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm-commons/5.2/asm-commons-5.2.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm-tree/5.2/asm-tree-5.2.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/ow2/asm/asm-util/5.2/asm-util-5.2.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/commons/commons-vfs2/2.1/commons-vfs2-2.1.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.3.0/config-1.3.0.jar" "/home/andrew/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/snapshots/org/ensime/core_2.12/2.0.0-SNAPSHOT/core_2.12-2.0.0-SNAPSHOT.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/googlecode/java-diff-utils/diffutils/1.3.0/diffutils-1.3.0.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/lihaoyi/fastparse-utils_2.12/0.4.2/fastparse-utils_2.12-0.4.2.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/lihaoyi/fastparse_2.12/0.4.2/fastparse_2.12-0.4.2.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/guava/guava/21.0/guava-21.0.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/h2database/h2/1.4.193/h2-1.4.193.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/slf4j/jcl-over-slf4j/1.7.23/jcl-over-slf4j-1.7.23.jar" "/home/andrew/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/snapshots/org/ensime/jerky_2.12/2.0.0-SNAPSHOT/jerky_2.12-2.0.0-SNAPSHOT.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/slf4j/jul-to-slf4j/1.7.23/jul-to-slf4j-1.7.23.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.1/logback-classic-1.2.1.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.1/logback-core-1.2.1.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/lucene/lucene-analyzers-common/6.4.1/lucene-analyzers-common-6.4.1.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/apache/lucene/lucene-core/6.4.1/lucene-core-6.4.1.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/typelevel/macro-compat_2.12/1.1.1/macro-compat_2.12-1.1.1.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-buffer/4.1.8.Final/netty-buffer-4.1.8.Final.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-codec/4.1.8.Final/netty-codec-4.1.8.Final.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-codec-http/4.1.8.Final/netty-codec-http-4.1.8.Final.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-common/4.1.8.Final/netty-common-4.1.8.Final.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-handler/4.1.8.Final/netty-handler-4.1.8.Final.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-resolver/4.1.8.Final/netty-resolver-4.1.8.Final.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/io/netty/netty-transport/4.1.8.Final/netty-transport-4.1.8.Final.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-refactoring/org.scala-refactoring.library_2.12.1/0.12.0/org.scala-refactoring.library_2.12.1-0.12.0.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.0/reactive-streams-1.0.0.jar" "/home/andrew/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/snapshots/org/ensime/s-express_2.12/2.0.0-SNAPSHOT/s-express_2.12-2.0.0-SNAPSHOT.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-debugger/scala-debugger-api_2.12/1.1.0-M3/scala-debugger-api_2.12-1.1.0-M3.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-debugger/scala-debugger-macros_2.12/1.1.0-M3/scala-debugger-macros_2.12-1.1.0-M3.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.0.4/scala-parser-combinators_2.12-1.0.4.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar" "/home/andrew/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/snapshots/org/ensime/server_2.12/2.0.0-SNAPSHOT/server_2.12-2.0.0-SNAPSHOT.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/chuusai/shapeless_2.12/2.3.2/shapeless_2.12-2.3.2.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.23/slf4j-api-1.7.23.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/typesafe/slick/slick_2.12/3.2.0-RC1/slick_2.12-3.2.0-RC1.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/lihaoyi/sourcecode_2.12/0.1.3/sourcecode_2.12-0.1.3.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/com/github/fommil/spray-json-shapeless_2.12/1.3.0/spray-json-shapeless_2.12-1.3.0.jar" "/home/andrew/.coursier/cache/v1/https/repo1.maven.org/maven2/io/spray/spray-json_2.12/1.3.2/spray-json_2.12-1.3.2.jar" "/home/andrew/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/snapshots/org/ensime/swanky_2.12/2.0.0-SNAPSHOT/swanky_2.12-2.0.0-SNAPSHOT.jar" "/usr/lib/jvm/java-8-openjdk/lib/tools.jar" "/home/andrew/.coursier/cache/v1/https/oss.sonatype.org/content/repositories/snapshots/org/ensime/util_2.12/2.0.0-SNAPSHOT/util_2.12-2.0.0-SNAPSHOT.jar")
```

**Comment by ktonga** [comment] 2017-03-27 01:44
Ok, it seems you're trying to use server 2.0, You will need to add this to your vimrc:

```VimL
let ensime_server_v2=1
```

This is a temporary hack and will be removed once we implement something better :)

Give it a try and lemme know if it fixes your ploblem

**Comment by andykais** [comment] 2017-03-27 18:28
sure, added that and now have a new error:
```log
Error detected while processing VimLeave Auto commands for "*.scala":                                                                                                                                                             
error caught in request handler '/home/andrew/.dotfiles/configs-xdg-dir/nvim/plugged/ensime-vim/rplugin/python/ensime.py:autocmd:VimLeave:*.scala ('src/main/scala/http/RootService.scala',)':                                    
Traceback (most recent call last):                                                                                                                                                                                                
  File "/home/andrew/.dotfiles/configs-xdg-dir/nvim/plugged/ensime-vim/rplugin/python/ensime.py", line 168, in au_vim_leave                                                                                                       
    super(NeovimEnsime, self).au_vim_leave(*args, **kwargs)                                                                                                                                                                       
  File "/home/andrew/.dotfiles/configs-xdg-dir/nvim/plugged/ensime-vim/ensime_shared/ensime.py", line 22, in wrapper2                                                                                                             
    create_client=create_client)                                                                                                                                                                                                  
  File "/home/andrew/.dotfiles/configs-xdg-dir/nvim/plugged/ensime-vim/ensime_shared/ensime.py", line 95, in current_client                                                                                                       
    create_client=create_client)                                                                                                                                                                                                  
  File "/home/andrew/.dotfiles/configs-xdg-dir/nvim/plugged/ensime-vim/ensime_shared/ensime.py", line 105, in client_for                                                                                                          
    client = self.create_client(config_path)                                                                                                                                                                                      
  File "/home/andrew/.dotfiles/configs-xdg-dir/nvim/plugged/ensime-vim/ensime_shared/ensime.py", line 124, in create_client                                                                                                       
    self._                                                                                                                                                                                                                        
Error detected while processing function remote#define#AutocmdBootstrap:                                                                                                                                                          
line    7:                                                                                                                                                                                                                        
E171: Missing :endif
```
vim plug says that `ensime-vim` is up-to-date

**Comment by ktonga** [comment] 2017-03-27 21:39
Could you please tell me the steps to reproduce it? I have a similar setup to yours and I'm not being able to make this error happen.

Have you run `:UpdateRemotePlugins` after updating with VimPlug?

**Comment by andykais** [comment] 2017-03-27 23:44
ok Ill try to simplify it. 

I have reduced my `init.vim` to this
```vim
"------------------------------------------------------------
"Vim-Plug Package Manager
call plug#begin('~/.vim/plugged')
Plug 'derekwyatt/vim-scala'
Plug 'ensime/ensime-vim', {'do': ':UpdateRemotePlugins'}
call plug#end()

let ensime_server_v2=1
```
I am running a project in this [folder](https://github.com/andykais/telebum2/tree/master/services/web-api) of my project.

In the project I removed all `target`, `scala-2.12`, `java` folders before running. In sbt I run
```sbt
[info] Loading global plugins from /home/andrew/.sbt/0.13/plugins
[info] Loading project definition from /home/andrew/Build/dev/telebum2/services/web-api/project
[info] Set current project to telebum-api (in build file:/home/andrew/Build/dev/telebum2/services/web-api/)
> 
> 
> compile
[info] Updating {file:/home/andrew/Build/dev/telebum2/services/web-api/}web-api...
[info] Resolving jline#jline;2.14.1 ...
[info] Done updating.
[info] Compiling 7 Scala sources to /home/andrew/Build/dev/telebum2/services/web-api/target/scala-2.12/classes...
[success] Total time: 16 s, completed Mar 27, 2017 7:29:21 PM
>
> ensimeConfig
[info] ENSIME update.
[info] Resolving jline#jline;2.14.1 ...
[info] ENSIME processing web-api (telebum-api)
[info] Creating /home/andrew/Build/dev/telebum2/services/web-api/target/scala-2.12/src_managed/test. Read about `ensimeIgnoreMissingDirectories`
[info] Creating /home/andrew/Build/dev/telebum2/services/web-api/src/test/scala-2.12. Read about `ensimeIgnoreMissingDirectories`
[info] Creating /home/andrew/Build/dev/telebum2/services/web-api/src/test/scala. Read about `ensimeIgnoreMissingDirectories`
[info] Creating /home/andrew/Build/dev/telebum2/services/web-api/src/test/java. Read about `ensimeIgnoreMissingDirectories`
[info] Creating /home/andrew/Build/dev/telebum2/services/web-api/target/scala-2.12/src_managed/main. Read about `ensimeIgnoreMissingDirectories`
[info] Creating /home/andrew/Build/dev/telebum2/services/web-api/src/main/scala-2.12. Read about `ensimeIgnoreMissingDirectories`
[info] Creating /home/andrew/Build/dev/telebum2/services/web-api/src/main/java. Read about `ensimeIgnoreMissingDirectories`
```

Then, with `nvim` I open a file in `src/`, run `:EnTypeCheck` and get the previously mentioned error ending with "missing an endif"

**Comment by travishegner** [comment] 2017-03-31 15:15
I'm having a similar issue using nvim.

I think I may have potentially narrowed it down to the 'EnTick' function not being registered correctly within nvim. The traceback is cut off much like above, but I continued stepping through, and found that if I run `:call timer_start(1000, 'EnTick', {'repeat': -1})` manually within an nvim session, I get a message that states `Function EnTick doesn't exist`.

This happens even though In`rplugin/ensime.py`, the `EnTick` function is clearly defined. I was able to prevent the errors from happening by disabling the timer manually in `ensime_shared/ticker.py` by adding a `self.has_timers = False` just before the check for timers calls `self._start_refresh_timer()`, effectively preventing the `Ticker()` from ever calling nvim's `timer_start()` function.

I can try to help troubleshoot with guided directions, but beware that I know almost nothing about writing nvim plugins, and I've never used python professionally.

**Comment by ktonga** [comment] 2017-03-31 21:05
@travishegner That function was added recently, have you run `:UpdateRemotePlugins` after updating?

**Comment by travishegner** [comment] 2017-04-04 12:20
@ktonga, indeed, I have. My issue is probably more related to #388.

**Comment by Wonicon** [comment] 2017-04-05 04:32
I ran into the same problem with VIM 8.0.
After executing `:PluginUpdate` in Vundle, the error report in VIM disappeared, but `./ensime_cache/ensime-vim.log` still showed the same handshake error.
But when I unintendedly add `let ensime_server_v2=1` found in this issue to my `.vimrc`, and everything starts to work.

**Comment by ktonga** [comment] 2017-04-05 15:16
I'm closing this issue as the handshake 404 is solved by adding `let ensime_server_v2=1` to `vimrc`.
For those whose problem isn't solved by this hack and still have the `E171: Missing :endif` error let's move the discussion to #388

**Closed by ktonga** 2017-04-05 15:16 UTC
