### ISSUE TITLE
Always show full type?

### ISSUE THREAD

**Issue by dubiousdavid** [ensime/ensime-vim#396] opened 2017-05-30 16:17 UTC
Is there a way to always show the full type without having to manually call `:EnToggleFullType`?

**Comment by ktonga** [comment] 2017-05-31 00:28
I guess you can call the command in your vimrc to force it.
We had a discussion about it a while back just in case you're interested #290. SPOILER I'm on your side :)
You can add your thoughts on that issue, feedback is always welcome.

Closing this issue as a duplicate of #290

**Closed by ktonga** 2017-05-31 00:28 UTC
