### ISSUE TITLE
launch saveClasspath task in the background

### ISSUE THREAD

**Issue by yazgoo** [ensime/ensime-vim#29] opened 2015-09-08 06:22 UTC
Before launching ensime, there's a step to find ensime classpath called saveClasspath.
This step should be launched in the background.
Also, since it is a long step that can fail, vim-ensime should:
- log its output
- tell what it's doing

**Comment by yazgoo** [comment] 2015-09-09 06:59
There is an issue with Popen screwing vim stdin when launching saveclasspath which has to be fixed

**Comment by yazgoo** [comment] 2015-09-10 11:06
Here is the core of the problem:

````shell
python
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess; f = open("/dev/null", "rw"); subprocess.Popen(["sbt"], stdout=f, stderr=f, stdin=f)
<subprocess.Popen object at 0x10fc03950>
>>> ^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[A^[[Aimport subprocess; f = open("/dev/null", "rw"); subprocess.Popen(["sbt"], stdout=f, stderr=f, stdin=f)
````

**Comment by rorygraves** [comment] 2015-09-10 11:19
Ah, I see the prblem - running sbt without another ocmmand will run a prompt - you want ["sbt", "saveClasspath" ]

**Comment by rorygraves** [comment] 2015-09-10 11:22
also I think you can set stderr=subprocess.STDOUT and leave stdin undefined.

**Comment by rorygraves** [comment] 2015-09-10 11:22
will push my sublime code shortly for comparsion/sharing

**Comment by rorygraves** [comment] 2015-09-10 11:27
Have a look at https://github.com/rorygraves/ensime-sublime/blob/ST3/server.py#L73  - this is the generic method I have been working on for this.,

**Comment by yazgoo** [comment] 2015-09-10 11:31
@rorygraves this also happens when using ["sbt", "saveClasspath"].
I've opened:
http://stackoverflow.com/questions/32500630/stdin-reading-blocking-when-running-sbt-with-python-subprocess-popen

**Comment by rorygraves** [comment] 2015-09-10 11:34
Ah cool - I don't understand your initial problem - you are saying the subprocess is basically making the console not work correctly?

**Comment by yazgoo** [comment] 2015-09-10 11:35
Yeah, and even in non-interactive mode:

````shell
$ python
Python 2.7.10 (default, Jul 13 2015, 12:05:58)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess; f = open("/dev/null", "rw"); subprocess.Popen(["sbt", "version"], stdout=f, stderr=subprocess.STDOUT, stdin=f)
<subprocess.Popen object at 0x10e3a2950>
>>> import subprocess; f = open("/dev/null", "rw"); subprocess.Popen(["sbt", "version"], stdout=f, stderr=subprocess.STDOUT, stdin=f)^[[A^[[A^[[A^[[A
````

**Comment by rorygraves** [comment] 2015-09-10 11:43
Ouch - I use subprocess.call not sure of the differences - I  think that Sublime uses Python 3.3 as well so I'm not sure I'm able to add anything.  Can you move to 3.3?

**Comment by yazgoo** [comment] 2015-09-10 11:54
I just tried with 3.4.3 and got the same behavior.

**Comment by jvican** [comment] 2015-09-11 08:39
I can help. I will look into this as well.

**Comment by yazgoo** [comment] 2015-09-14 12:12
I've tried all the solutions mentioned on stackoverflow plus anything I could think of, so I'm putting this on standby for now.

**Comment by jvican** [comment] 2015-09-23 18:01
I have tried to find a solution, but no luck. However, is this behavior making the plugin not to work well?

**Comment by vito-c** [comment] 2015-12-22 08:53
I think these are related: https://github.com/ensime/ensime-vim/issues/129

**Comment by vito-c** [comment] 2015-12-22 09:21
probably want to investigate using `Popen.communicate` as well? https://docs.python.org/2/library/subprocess.html#subprocess.Popen.communicate

**Comment by yazgoo** [comment] 2015-12-22 11:44
I think I also tried it with no success.

**Comment by jvican** [comment] 2016-01-06 14:34
My guess is that `sbt` is misbehaving when there is no pseudo-tty to interact with the user (probably because of `jline`). The solution is to use a python module to run the commands in a pseudo-tty. Let's install `pexpect` via pip (`pip3 install pexpect` for Python 3.x).
  
Then, run the following:
  
```python
import pexpect, sys
f = open("sbt.log", "w+")
# Use `spawnu` for Python3, `spawn` otherwise
sbt = pexpect.spawnu("sbt -Dsbt.log.noformat=true \"version\" \"another-command\"", logfile=f)

# Do whatever is needed while sbt is running

# Force the process to expect EOF and file to be written
sbt.expect(pexpect.EOF)
```
Tested in Python 3.4.3 (Gentoo Linux) and works.
  
I am working on a PR right now. Let me know what you think of this solution and if you consider feasible to use a external python module like `pexpect`.

**Comment by jvican** [comment] 2016-01-08 11:23
Well, I am doing a PR out of this. Also, I will be working on new features to add to ensime-vim.

**Comment by jvican** [comment] 2016-01-08 16:38
Whoops, after several tries there is no luck with this. I think that I have spotted the problem. `ConsoleReader` from `jline` is somehow getting the stdin from the system and not from the file descriptors because no matter how you try it you cannot redirect stdin. Also, as you write in your keyboard, jline detects that you are writing by stdin and buffers (and echoes) everything it gets.
  
So far, there is no way to do this. If somehow we could avoid that behavior of `jline`...
Anyway, I drop this and I will focus on the missing features. Cheers.

**Comment by jvican** [comment] 2016-01-27 23:09
This is a pretty unnecessary task because sync between client and forked sbt is difficult and requires locking. In my view it does not worth a try. I would close this...

**Comment by jvican** [comment] 2016-02-12 08:31
OK, last PR fixes some problems with `EnClasspath` in Neovim, like the conflict of stdout caused by the interactive mode of sbt that forced to restart it. In fact, `sbt` is now executed asynchronously (`terminal` feature) but the main process waits until it's finished.
  
So, the bug is fixed and the feature of running `EnClasspath` async is there but it's not being used. If anyone is interested in this, we could reopen the ticket.

**Closed by jvican** 2016-02-12 08:31 UTC
Labels: bug, ensime_launcher, low priority
