### ISSUE TITLE
IndexError('list index out of range',)

### ISSUE THREAD

**Issue by Ferenc-** [ensime/ensime-vim#121] opened 2015-12-03 02:08 UTC
The `:EnDebug` gives me the following:
```
Error detected while processing function remote#define#CommandBootstrap:
line    5:
IndexError('list index out of range',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/neovim/msgpack_rpc/session.py", line 177, in handler
    rv = self._request_cb(name, args)
  File "/usr/lib/python2.7/site-packages/neovim/api/common.py", line 237, in filter_request_cb
    walk(self._in, args, self, name, 'request'))
  File "/usr/lib/python2.7/site-packages/neovim/plugin/host.py", line 65, in _on_request
    rv = handler(*args)
  File "/home/ferenc/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py", line 574, in com_en_debug_start
    self.with_current_client(lambda c: c.debug_start(args, range))
  File "/home/ferenc/.config/nvim/plugged/ensime-vim/rplugin/python/ensime.py", line 515, in with_current_client
    return proc(c)
IndexError: list index out of range

Press ENTER or type command to continue

````
neovim python module
````
> pip list | grep neovim
neovim (0.0.38)
````
neovim
````
> nvim --version
NVIM v0.1.0-157-g0ee3398 (compiled Dec  3 2015 00:59:24)
Commit: 0ee33981e8967bab75427214b432e22ebcf40d6f
Build type: Release
Compilation: /usr/bin/cc -Wconversion -O2 -DNDEBUG -DDISABLE_LOG -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wvla -fstack-protector-strong -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -DHAVE_CONFIG_H -I/tmp/neovim/build/config -I/tmp/neovim/src -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include/luajit-2.0 -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/tmp/neovim/.deps/usr/include -I/usr/include -I/tmp/neovim/build/src/nvim/auto -I/tmp/neovim/build/include
Compiled by ferenc@workstation

Optional features included (+) or not (-): +acl   +iconv    +jemalloc
For differences from Vim, see :help vim-differences

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/home/ferenc/COMPILED/neovim/share/nvim"

````

**Comment by yazgoo** [comment] 2015-12-03 07:58
Thanks @Ferenc- , could you please also provide .ensime-cache/ensime-vim.log and .ensime_cache/server.log when this happens ?

**Comment by Ferenc-** [comment] 2015-12-03 09:41
```
> cat .ensime_cache/server.log
10:41:06.448 INFO  None a.e.s.Slf4jLogger - Slf4jLogger started
10:41:06.455 DEBUG EventStream(akka://ENSIME) a.e.EventStream - logger log1-Slf4jLogger started
10:41:06.458 DEBUG EventStream(akka://ENSIME) a.e.EventStream - Default Loggers started
10:41:06.486 INFO  None o.a.c.v.i.StandardFileSystemManager - Using "/tmp/vfs_cache" as temporary files store.
10:41:06.527 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/0 a.i.TcpListener - Successfully bound to /127.0.0.1:40115
10:41:06.530 INFO  akka://ENSIME/user/ensime-main/tcp-server o.e.s.t.TCPServer - Bound server on port 40115
10:41:06.530 INFO  None o.e.s.PortUtil$ - creating portfile /mnt/backup/Devel/Scala/my_project/.ensime_cache/port
10:41:06.972 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - Environment:
  OS : Linux
  Java : Java HotSpot(TM) 64-Bit Server VM 25.66-b17, Java(TM) SE Runtime Environment 1.8.0_66-b17
  Scala : version 2.11.6
  Ensime : 0.9.10-SNAPSHOT
10:41:06.973 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - Successfully bound to /127.0.0.1:45867
10:41:06.977 INFO  akka://ENSIME/user/ensime-main o.e.s.ServerActor - ENSIME HTTP on /127.0.0.1
10:41:06.977 INFO  None o.e.s.PortUtil$ - creating portfile /mnt/backup/Devel/Scala/my_project/.ensime_cache/http
10:41:07.311 INFO  None o.e.i.DatabaseService - creating the search database...
10:41:07.487 WARN  None c.j.b.BoneCPConfig - JDBC username was not set in config!
10:41:07.939 INFO  None o.e.i.DatabaseService - ... created the search database
10:41:07.950 INFO  None o.e.i.ClassfileWatcher - Setting up new file watchers
```

```
>cat .ensime_cache/ensime-vim.log
2015-12-03 10:41:28.797349: debug_start: in
2015-12-03 10:41:33.775044: teardown: in
```

**Comment by yazgoo** [comment] 2015-12-03 12:27
Thanks @Ferenc-,
The problem is that EnDebugStart expects a class as a parameter (as documented in https://github.com/ensime/ensime-vim/blob/master/doc/ensime-vim.txt ).
It shouldn't throw an exception, though, hence #122.

**Comment by yazgoo** [comment] 2015-12-03 14:08
Closing this, please re-open if necessary.

**Closed by yazgoo** 2015-12-03 14:08 UTC
