### ISSUE TITLE
:EnRename doesn't work across files

### ISSUE THREAD

**Issue by stevendobay** [ensime/ensime-vim#310] opened 2016-07-15 18:19 UTC
Hello, 

My setup can be found in [this issue](https://github.com/ensime/ensime-vim/issues/306) and the problem is in the title. Is it because of the nature of ensime or is it a bug?

**Comment by ches** [comment] 2016-07-15 18:38
More detail would be helpful here—it would be really good if you used [the issue template][1] that GitHub pre-fills in for you. I know we have some boilerplate in there that should probably be trimmed (creating an example reproduction project is often overkill), but at least following the parts of specific steps to reproduce plus expected/actual behavior will help us help you faster and reduce back-and-forth communication that is an energy drain.

Now, I do believe `:EnRename` is buggy and we should log an issue for it. `:EnDeclaration` however has not been a problem for me. Can you elaborate on the problem you're seeing?

[1]: https://github.com/ensime/ensime-vim/blob/master/.github/ISSUE_TEMPLATE.MD

**Comment by rorygraves** [comment] 2016-07-15 18:41
I suspect you are talking about when the second/other files are not open?  Is you file successfully compiled.  Rename has a known limitation because we rely on the presentation compiler to do the work and it will not see files not loaded in.  (We are working on the graphpocolpyse to ensure we load the right set of files to make it work).  EnDeclaration could fail if the project never hit a compilable state.  - As @ches says, we need more information.

**Comment by stevendobay** [comment] 2016-07-15 18:49
Sorry, more details:

1. Setup the environment as in the referenced issue

2. addSbtPlugin("org.ensime" % "sbt-ensime" % "1.0.0") to the ~/.sbt/0.13/plugins/plugins.sbt

3. Created the project directory:

```
mkdir test ; cd test 

vim build.sbt
```

4. build.sbt content:

```
name := "test"

version := "1.0

scalaVersion := "2.11.8"
```

5. created "src/main/scala/tt" package

6. Added Source.scala:

```scala
package tt

object Source {
  val one = 1 // renaming "one" here doesn't affect the next file
}
```

7. Added Main.scala:

```scala
object Main extends App {
  var variable = "a"
  println(tt.Source.one) 
  println(variable)
}
```

8. Run in sbt:

```shell
run
ensimeConfig
```

9. Added "autocmd BufWritePost *.scala :EnTypeCheck" to .vimrc

10. Opened Main.scala, EnTypeCheck worked, EnRename and EnDeclaration worked only locally

**Comment by rorygraves** [comment] 2016-07-15 18:52
Ok, i'm suprised the EnDeclaration does not work - over to @ches  to investigate that one.  The first one is a known issue with rename I believe (specifically if the file is not open it is not loaded into the presentation compiler and the rename misses it.  Try opening both buffers in vim and rename should work.  As mentioned this is actively being worked on.

**Comment by stevendobay** [comment] 2016-07-15 18:56
@rorygraves I've tried to open both files but no luck.

**Comment by stevendobay** [comment] 2016-07-15 18:59
I've tried a full reinstall but no luck.

**Comment by rorygraves** [comment] 2016-07-15 19:00
Thanks @stevendobay , i will have to hand over to @ches for investigation on the vim - (I'm not a vim user).  The server log would be interesting to see what requests are flowing.

**Comment by stevendobay** [comment] 2016-07-15 19:04
UPDATE: EnDeclaration is working after the reinstall but EnRename is not.

The server.log:

```
21:01:46.754 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - New connection accepted
21:01:46.761 DEBUG akka://ENSIME/system/IO-TCP/selectors/$a/1 a.i.TcpListener - New connection accepted
21:01:46.771 DEBUG akka://ENSIME/user/$c o.e.s.ConnectionHandler - received handled message FullTypeCheckCompleteEvent
21:01:46.771 DEBUG akka://ENSIME/user/$c o.e.s.ConnectionHandler - received handled message AnalyzerReadyEvent
21:01:46.771 DEBUG akka://ENSIME/user/$c o.e.s.ConnectionHandler - received handled message IndexerReadyEvent
21:01:46.771 DEBUG akka://ENSIME/user/ensime-main/StreamSupervisor-0/flow-34-0-actorRefSource a.s.i.ActorRefSourceActor - Dropping element because there is no downstream demand: [RpcResponseEnvelope(None,FullTypeCheckCompleteEvent)]
21:01:46.771 DEBUG akka://ENSIME/user/ensime-main/StreamSupervisor-0/flow-34-0-actorRefSource a.s.i.ActorRefSourceActor - Dropping element because there is no downstream demand: [RpcResponseEnvelope(None,AnalyzerReadyEvent)]
21:01:46.771 DEBUG akka://ENSIME/user/ensime-main/StreamSupervisor-0/flow-34-0-actorRefSource a.s.i.ActorRefSourceActor - Dropping element because there is no downstream demand: [RpcResponseEnvelope(None,IndexerReadyEvent)]
21:01:46.785 DEBUG akka://ENSIME/user/ensime-main/StreamSupervisor-0/flow-32-0-unknown-operation a.a.RepointableActorRef - Aborting tcp connection because of upstream failure: requirement failed: Cannot pull port twice
scala.Predef$.require(Predef.scala:224)
akka.stream.stage.GraphStageLogic.pull(GraphStage.scala:420)
akka.http.impl.engine.server.HttpServerBluePrint$Prot
21:01:46.787 DEBUG akka://ENSIME/user/$c/0 o.e.s.RequestHandler - ConnectionInfoReq
21:01:46.787 DEBUG akka://ENSIME/user/ensime-main/project o.e.c.Project - received handled message ConnectionInfoReq in state handleRequests
21:01:46.787 DEBUG akka://ENSIME/user/$c/0 o.e.s.RequestHandler - received handled message ConnectionInfo(None,EnsimeImplementation(ENSIME),1.0) in state receive

```

The ensime-vim.log:

```
2016-07-15 21:01:46.732504: Initializing project - /home/steven/Workspace/test
2016-07-15 21:01:46.732627: __init__: in
2016-07-15 21:01:46.752138: [(<frame object at 0x7fa8dad4a450>, '/home/steven/.vim/bundle/ensime-vim/ensime_shared/ensime.py', 199, 'lazy_initialize_ensime', ['                self.log(str(inspect.stack()))\n'], 0), (<frame object at 0x7fa8db1ce638>, '/home/steven/.vim/bundle/ensime-vim/ensime_shared/ensime.py', 225, 'setup', ['        return self.running and lazy_initialize_ensime() and ready_to_connect()\n'], 0), (<frame object at 0x55893a6c3f90>, '/home/steven/.vim/bundle/ensime-vim/ensime_shared/ensime.py', 1111, 'client_for', ['            if client.setup(quiet=quiet, bootstrap_server=bootstrap_server):\n'], 0), (<frame object at 0x55893a6d57b0>, '/home/steven/.vim/bundle/ensime-vim/ensime_shared/ensime.py', 1086, 'current_client', ['                create_client=create_client)\n'], 0), (<frame object at 0x55893a77aa30>, '/home/steven/.vim/bundle/ensime-vim/ensime_shared/ensime.py', 1029, 'wrapper2', ['                create_client=create_client)\n'], 0), (<frame object at 0x7fa8dc6ca228>, '<string>', 3, '<module>', None, None)]
2016-07-15 21:01:46.752186: setup(quiet=True, bootstrap_server=False) called by wrapper2()
2016-07-15 21:01:46.754109: connect_ensime_server: in
2016-07-15 21:01:46.779112: send_request: in
2016-07-15 21:01:46.779244: send: in
2016-07-15 21:01:46.779295: send: {"callId": 0, "req": {"typehint": "ConnectionInfoReq"}}
2016-07-15 21:01:46.779565: message: in
2016-07-15 21:01:46.779611: [ensime] Server has been started...
2016-07-15 21:01:47.233174: Websocket exception: [Errno 104] A kapcsolatot bontotta a távoli fél
2016-07-15 21:01:47.233229: teardown: in
2016-07-15 21:01:47.233249: shutdown_server: in
2016-07-15 21:01:47.233345: disable_plugin: in
2016-07-15 21:01:47.233369: ~/.vim/bundle/ensime-vim
2016-07-15 21:01:47.233433: ~/.vim/bundle/ensime-vim/after
2016-07-15 21:01:47.233475: ~/.vim/bundle/ensime-vim/plugin_integrations/syntastic
```

**Comment by ches** [comment] 2016-07-15 19:06
Thanks for the further info, that helps.

So yeah, the refactoring is broken, and I believe there are bugs with it that are specific to the Vim client and not just the limitations @rorygraves referred to.

`:EnDeclaration` works fine for me though, I've set up your exact repro project. Having the cursor on either `Source`, `one`, or `variable` in `Main.scala` do what's expected. Let's see if there's something else going on in your case.

**Comment by stevendobay** [comment] 2016-07-15 19:08
@ches

> :EnDeclaration works fine for me though, I've set up your exact repo project.

True, now it does work for me after the reinstall, see the heading of my comment about the logs.

**Comment by ches** [comment] 2016-07-15 19:25
Are you seeing a WebSocket exception consistently when you restart Vim, like shown in your `ensime-vim.log` above?

This does occasionally happen, for me restarting Vim—which should restart the server—typically resolves it. Since it's transient and there's still a lot of other stuff to do, I haven't tried to debug it in earnest yet. If this happens consistently or even just "too often" for you please let us know.

We could probably indicate the startup failure better in the Vim UI but I believe right now you'll just notice that the startup status messages don't get echoed in Vim, so that's the clue until we improve the reporting.

I'm trying to work on test suite improvements which should of course be an aid to robustness and regression prevention across the board…

**Comment by stevendobay** [comment] 2016-07-15 20:14
No, I don't see that often. Here is a new start and try to refactor:

```scala
2016-07-15 22:11:05.052093: Initializing project - /home/steven/Workspace/test
2016-07-15 22:11:05.052221: __init__: in
2016-07-15 22:11:05.073587: [(<frame object at 0x7fdd05baf450>, '/home/steven/.vim/bundle/ensime-vim/ensime_shared/ensime.py', 199, 'lazy_initialize_ensime', ['                self.log(str(inspect.stack()))\n'], 0), (<frame object at 0x7fdd06033638>, '/home/steven/.vim/bundle/ensime-vim/ensime_shared/ensime.py', 225, 'setup', ['        return self.running and lazy_initialize_ensime() and ready_to_connect()\n'], 0), (<frame object at 0x562cde9fcd00>, '/home/steven/.vim/bundle/ensime-vim/ensime_shared/ensime.py', 1111, 'client_for', ['            if client.setup(quiet=quiet, bootstrap_server=bootstrap_server):\n'], 0), (<frame object at 0x562cdeba0d70>, '/home/steven/.vim/bundle/ensime-vim/ensime_shared/ensime.py', 1086, 'current_client', ['                create_client=create_client)\n'], 0), (<frame object at 0x562cdea11680>, '/home/steven/.vim/bundle/ensime-vim/ensime_shared/ensime.py', 1029, 'wrapper2', ['                create_client=create_client)\n'], 0), (<frame object at 0x7fdd0752f228>, '<string>', 3, '<module>', None, None)]
2016-07-15 22:11:05.073635: setup(quiet=True, bootstrap_server=False) called by wrapper2()
2016-07-15 22:11:05.075484: message: in
2016-07-15 22:11:05.075521: [ensime] Server has been started...
2016-07-15 22:11:06.383149: connect_ensime_server: in
2016-07-15 22:11:06.831287: send_request: in
2016-07-15 22:11:06.831366: send: in
2016-07-15 22:11:06.831393: send: {"callId": 0, "req": {"typehint": "ConnectionInfoReq"}}
2016-07-15 22:11:07.517876: unqueue: result received {
  "callId": 0,
  "payload": {
    "typehint": "ConnectionInfo",
    "implementation": {
      "name": "ENSIME"
    },
    "version": "1.0"
  }
}
2016-07-15 22:11:07.518039: handle_incoming_response: in {u'implementation': {u'name': u'ENSIME'}, u'typehint': u'ConnectionInfo', u'version': u'1.0'}
2016-07-15 22:11:07.518094: Response {u'implementation': {u'name': u'ENSIME'}, u'typehint': u'ConnectionInfo', u'version': u'1.0'} has not been handled
2016-07-15 22:11:07.732187: unqueue: result received {
  "payload": {
    "typehint": "IndexerReadyEvent"
  }
}
2016-07-15 22:11:07.732271: handle_incoming_response: in {u'typehint': u'IndexerReadyEvent'}
2016-07-15 22:11:07.732302: message: in
2016-07-15 22:11:07.732317: [ensime] Indexer is ready
2016-07-15 22:11:08.231864: unqueue: result received {
  "payload": {
    "typehint": "SendBackgroundMessageEvent",
    "detail": "Initializing Analyzer. Please wait...",
    "code": 105
  }
}
2016-07-15 22:11:08.231944: handle_incoming_response: in {u'code': 105, u'typehint': u'SendBackgroundMessageEvent', u'detail': u'Initializing Analyzer. Please wait...'}
2016-07-15 22:11:08.231970: Response {u'code': 105, u'typehint': u'SendBackgroundMessageEvent', u'detail': u'Initializing Analyzer. Please wait...'} has not been handled
2016-07-15 22:11:08.703624: unqueue: result received {
  "payload": {
    "typehint": "AnalyzerReadyEvent"
  }
}
2016-07-15 22:11:08.703722: handle_incoming_response: in {u'typehint': u'AnalyzerReadyEvent'}
2016-07-15 22:11:08.703754: message: in
2016-07-15 22:11:08.703773: [ensime] Analyzer is ready
2016-07-15 22:11:09.276307: unqueue: result received {
  "payload": {
    "typehint": "FullTypeCheckCompleteEvent"
  }
}
2016-07-15 22:11:09.276406: handle_incoming_response: in {u'typehint': u'FullTypeCheckCompleteEvent'}
2016-07-15 22:11:13.463019: rename: in
2016-07-15 22:11:15.407444: path: in
2016-07-15 22:11:15.407500: message: in
2016-07-15 22:11:15.407517: /home/steven/Workspace/test/src/main/scala/tt/Source.scala
2016-07-15 22:11:15.407568: 4 5
2016-07-15 22:11:15.407592: 33
2016-07-15 22:11:15.407606: 4 7
2016-07-15 22:11:15.407620: 35
2016-07-15 22:11:15.407640: send_request: in
2016-07-15 22:11:15.407684: send: in
2016-07-15 22:11:15.407710: send: {"callId": 1, "req": {"procId": 1, "typehint": "RefactorReq", "params": {"newName": "one", "start": 33, "typehint": "RenameRefactorDesc", "end": 36, "file": "/home/steven/Workspace/test/src/main/scala/tt/Source.scala"}, "interactive": false}}
2016-07-15 22:11:16.700417: unqueue: result received {
  "payload": {
    "typehint": "ClearAllScalaNotesEvent"
  }
}
2016-07-15 22:11:16.700529: handle_incoming_response: in {u'typehint': u'ClearAllScalaNotesEvent'}
2016-07-15 22:11:16.700568: Response {u'typehint': u'ClearAllScalaNotesEvent'} has not been handled
2016-07-15 22:11:16.700608: unqueue: result received {
  "callId": 1,
  "payload": {
    "typehint": "RefactorDiffEffect",
    "procedureId": 1,
    "refactorType": {
      "typehint": "Rename"
    },
    "diff": "/tmp/ensime-diff-870140323920444454.tmp"
  }
}
2016-07-15 22:11:16.700672: handle_incoming_response: in {u'procedureId': 1, u'refactorType': {u'typehint': u'Rename'}, u'typehint': u'RefactorDiffEffect', u'diff': u'/tmp/ensime-diff-870140323920444454.tmp'}
2016-07-15 22:11:16.700709: path: in
2016-07-15 22:11:16.703558: path: in
```

**Comment by fommil** [comment] 2016-12-01 16:10
this is fixed in the GSoC feature branch. It's also worth noting that the reporter has been saying not-very-nice things about ensime elsewhere (which goes beyond technical debate into personal insults, calling us "lazy") so I don't think he deserves our time or attention. https://m.reddit.com/r/scala/comments/5eu9if/intellij_vs_ensime/

**Closed by fommil** 2016-12-01 16:10 UTC
Labels: bug

**Comment by stevendobay** [comment] 2016-12-01 16:43
Being butthurt after hearing a critique is really childish. Btw, the insults were coming from YOU. You should really think about your attitude.
